---
layout: fs-post
title: <strong>Promise</strong>
categories: fastcampus
section: fastcampus
seq: 45
permalink: /:categories/:title
description:
---

* TOC
{:toc}

자바스크립트는 비동기 처리를 위한 하나의 패턴으로 콜백 함수를 사용한다. 하지만 전통적인 콜백 패턴은 가독성이 나쁘고 비동기 처리 중 발생한 에러의 예외 처리가 곤란하며 여러 개의 비동기 처리를 한번에 처리하는 것도 한계가 있다. ES6에서는 비동기 처리를 위한 또 다른 패턴으로 프로미스(Promise)를 도입하였다. 프로미스는 전통적인 콜백 패턴이 가진 단점을 보완하며 비동기 처리 시점을 명확하게 표현하는 장점이 있다.

# 1. 비동기 처리를 위한 콜백 패턴의 단점

## 1.1. 콜백 헬

먼저 ["44.3.4. GET 요청"](/fastcampus/rest-api#34-get-요청)에서 살펴본 바와 같이 GET 요청을 위한 함수를 작성해 보자.

```javascript
// GET 요청을 위한 비동기 함수
const get = url => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      // 서버로부터의 응답을 콘솔에 출력
      console.log(JSON.parse(xhr.response));
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
};

// https://jsonplaceholder.typicode.com은 Fake REST API를 제공하는 서비스이다.
// id가 1인 post를 취득
get('https://jsonplaceholder.typicode.com/posts/1');
/*
{
  "userId": 1,
  "id": 1,
  "title": "sunt aut facere ...",
  "body": "quia et suscipit ..."
}
*/
```

GET 요청을 위한 get 함수는 비동기 함수이다. 따라서 비동기 함수 내에서 서버의 응답 결과를 반환하거나 상위 스코프의 변수에 할당하면 기대한 대로 동작하지 않는다. 위 예제의 get 함수가 서버의 응답 결과를 반환하도록 수정해 보자.

```javascript
// GET 요청을 위한 비동기 함수
const get = url => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      // ① 서버로부터의 응답을 반환
      return JSON.parse(xhr.response);
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
};

// id가 1인 post를 취득
const response = get('https://jsonplaceholder.typicode.com/posts/1');

// ② 비동기 함수가 반환한 서버로부터의 응답을 출력한다.
console.log(response); // undefined
```

비동기 함수 get의 load 이벤트의 이벤트 핸들러에서 서버로부터의 응답 결과를 반환(①)하면 처리 순서가 보장되지 않는다. 즉, ②에서 get 함수가 반환한 값을 참조할 수 없다. 그 이유에 대해 살펴보자.

비동기 함수 get이 호출되면 get 함수의 실행 컨텍스트가 생성되고 실행 컨텍스트 스택(콜 스택)에 푸시되어 실행된다. get 함수는 xhr.onload 이벤트 핸들러 프로퍼티에 이벤트 핸들러를 바인딩하고 종료한다. 그리고 get 함수의 실행 컨텍스트는 실행 컨텍스트 스택에서 제거된다.

get 함수가 종료하면 곧바로 ②의 console.log가 호출되어 실행 컨텍스트 스택에 푸시되어 실행된다. console.log가 호출되기 직전에 load 이벤트가 발생하더라도 load 이벤트의 이벤트 핸들러는 결코 console.log보다 먼저 실행되지 않는다.

load 이벤트의 이벤트 핸들러는 load 이벤트가 발생하면 이벤트가 발생하면 즉시 실행되는 것이 아니다. load 이벤트가 발생하면 일단 태스크 큐로 푸시되고 실행 컨텍스트 스택(콜 스택)이 비면 그때 이벤트 루프에 의해 실행 컨텍스트 스택으로 푸시되어 실행된다.(이벤트 핸들러의 평가 -> 이벤트 핸들러의 실행 컨택스트 생성 -> 실행 컨텍스트 스택에 푸시 -> 이벤트 핸들러의 실행)

따라서 load 이벤트의 이벤트 핸들러가 실행되는 시점에는 콜 스택이 빈 상태이므로 ②의 console.log는 이미 종료된 이후이다. 만약 get 함수 이후에 console.log가 100번 호출된다해도 load 이벤트의 이벤트 핸들러는 모든 console.log가 종료한 이후에 실행된다. 즉, 비동기 함수인 get이 반환한 서버로부터의 응답이 변수에 할당되기 이전에 console.log가 먼저 호출되어 undefined가 출력된다.

이처럼 비동기 함수인 get이 취득한 서버로부터의 응답은 반환할 수 없다. 따라서 서버로부터의 응답에 대한 후속 처리를 위한 콜백 함수를 비동기 함수인 get에 전달해야 한다.

```javascript
// GET 요청을 위한 비동기 함수
const get = (url, callback) => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      // 서버로부터의 응답을 콜백 함수에 전달하면서 호출하여 응답에 대한 후속 처리를 한다.
      callback(JSON.parse(xhr.response));
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
};

// id가 1인 post를 취득
// 서버로부터의 응답에 대한 후속 처리를 위한 콜백 함수를 비동기 함수인 get에 전달해야 한다.
get('https://jsonplaceholder.typicode.com/posts/1', console.log);
/*
{
  "userId": 1,
  "id": 1,
  "title": "sunt aut facere ...",
  "body": "quia et suscipit ..."
}
*/
```

만일 비동기 함수의 처리 결과를 가지고 다른 비동기 함수를 호출해야 하는 경우, 함수의 호출이 중첩(nesting)이 되어 복잡도가 높아지는 현상이 발생하는데 이를 콜백 헬(Callback Hell)이라 한다. 아래 예제를 살펴보자.

```javascript
// GET 요청을 위한 비동기 함수
const get = (url, callback) => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      // 서버로부터의 응답을 콜백 함수에 전달하면서 호출하여 응답에 대한 후속 처리를 한다.
      callback(JSON.parse(xhr.response));
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
};

// id가 1인 post의 userId를 취득
get('https://jsonplaceholder.typicode.com/posts/1', ({ userId }) => {
  console.log(userId); // 1
  // 취득한 post의 userId로 user 정보를 취득
  get(`https://jsonplaceholder.typicode.com/users/${userId}`, userInfo => {
    console.log(userInfo); // {id: 1, name: "Leanne Graham", username: "Bret",...}
  });
});
```

위 예제를 살펴보면 GET 요청을 통해 서버로부터 응답(id가 1인 post)을 취득하고 이 데이터를 사용하여 또 다른 GET 요청을 한다. 콜백 헬은 가독성을 나쁘게 하며 실수를 유발하는 원인이 된다. 아래는 콜백 헬이 발생하는 전형적인 사례이다.

```javascript
get('/step1', a => {
  get(`/step2/${a}`, b => {
    get(`/step3/${b}`, c => {
      get(`/step4/${c}`, d => {
        console.log(d);
      });
    });
  });
});
```

## 1.2. 에러 처리의 한계

비동기식 처리를 위한 콜백 패턴의 문제점 중에서 가장 심각한 것은 에러 처리가 곤란하다는 것이다. 아래 예제를 살펴보자.

```javascript
try {
  setTimeout(() => { throw new Error('Error!'); }, 1000);
} catch (e) {
  // 에러를 캐치하지 못한다
  console.error('캐치한 에러', e);
}
```

try 블록 내에서 호출한 setTimeout 함수는 1초 후에 콜백 함수가 실행시키고 이 콜백 함수는 에러를 발생시킨다. 하지만 이 에러는 catch 블록에서 캐치되지 않는다. 그 이유에 대해 알아보자.

비동기 함수인 setTimeout이 호출되면 setTimeout 함수의 실행 컨텍스트가 생성되어 콜 스택에 푸시되어 실행된다. setTimeout은 비동기 함수이므로 콜백 함수가 호출되는 것을 기다리지 않고 즉시 종료되어 콜 스택에서 제거된다. 이후 타이머가 만료되면 setTimeout 함수의 콜백 함수는 태스트 큐로 푸시되고 콜 스택이 비어졌을 때 콜 스택으로 푸시되어 실행된다. 이때 setTimeout 함수는 이미 호출 스택에서 제거된 상태이다. 이것은 setTimeout 함수의 콜백 함수를 호출한 것은 setTimeout 함수가 아니다라는 것을 의미한다. setTimeout 함수의 콜백 함수의 호출자(caller)가 setTimeout 함수라면 콜 스택의 현재 실행중인 실행 컨텍스트가 콜백 함수의 실행 컨텍스트일 때, 현재 실행중인 실행 컨텍스트의 하위 실행 컨텍스트가 setTimeout 함수이어야 한다.

에러는 호출자(caller) 방향으로 전파된다. 하지만 위에서 살펴본 바와 같이 setTimeout 함수의 콜백 함수를 호출한 것은 setTimeout 함수가 아니다. 따라서 setTimeout 함수의 콜백 함수가 발생시킨 에러는 catch 블록에서 캐치되지 않는다.

지금까지 살펴본 비동기 함수의 콜백 헬이나 에러 처리의 한계를 극복하기 위해 ES6에서 프로미스(Promise)가 도입되었다.

# 2. 프로미스의 생성

프로미스는 Promise 생성자 함수를 통해 인스턴스화한다. Promise 생성자 함수는 비동기 처리를 수행할 콜백 함수를 인자로 전달받는데 이 콜백 함수는 resolve와 reject 함수를 인수로 전달받는다.

```javascript
// Promise 객체 생성
const promise = new Promise((resolve, reject) => {
  // Promise 함수의 콜백 함수 내부에서 비동기식 처리를 수행한다.
  if (/* 비동기 처리 성공 */) {
    resolve('result');
  } else { /* 비동기 처리 실패 */
    reject('failure reason');
  }
});
```

Promise 생성자 함수가 인수로 전달받은 콜백 함수 내부에서 비동기 처리를 수행한다. 이때 비동기 처리가 성공하면 콜백 함수의 인수로 전달받은 resolve 함수를 호출하고, 비동기 처리가 실패하면 reject 함수를 호출한다. 앞서 살펴보았던 비동기 함수 get가 프로미스를 사용하도록 수정해 보자.

```javascript
// GET 요청을 위한 비동기 함수
const promiseGet = url => {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open('GET', url);
    xhr.send();

    xhr.onload = () => {
      if (xhr.status === 200) {
        // 성공적으로 응답을 전달받으면 resolve 함수를 호출한다.
        resolve(JSON.parse(xhr.response));
      } else {
        // 에러 처리를 위해 reject 함수를 호출한다.
        reject(new Error(xhr.status));
      }
    };
  });
};

// promiseGet는 Promise 객체를 반환한다.
promiseGet('https://jsonplaceholder.typicode.com/posts/1');
```

프로미스로 구현된 비동기 함수는 함수 내부에서 Promise 객체를 생성하고 반환한다. 비동기 처리는 Promise 생성자 함수가 인수로 전달받은 콜백 함수 내부에서 수행한다. 만약 비동기 처리에 성공하면 비동기식 처리 결과를 resolve 함수에 인수로 전달하면서 호출하고, 비동기 처리에 실패하면 에러를 reject 함수에 인수로 전달하면서 호출한다.
프로미스로 구현된 비동기 함수는 Promise 객체를 반환한다. 반환된 Promise 객체는 비동기 처리가 성공(fulfilled)하였는지 또는 실패(rejected)하였는지 등의 상태(state) 정보를 갖는다.

| 상태       | 의미	  | 구현
|:----------|:------|:--
| pending   | 비동기 처리가 아직 수행되지 않은 상태 | resolve 또는 reject 함수가 아직 호출되지 않은 상태
| **fulfilled** | 비동기 처리가 수행된 상태 (성공) | resolve 함수가 호출된 상태
| **rejected**  | 비동기 처리가 수행된 상태 (실패) | reject 함수가 호출된 상태
| settled   | fulfilled 또는rejected와 상관 없이 pending 이 아닌 상태, 즉 비동기 처리가 수행된 상태 | resolve 또는 reject 함수가 호출된 상태

Promise 객체의 상태 정보는 resolve 또는 reject 함수를 호출하는 것으로 결정된다. resolve 또는 reject 함수를 호출할 때 전달한 비동기 처리 결과 또는 에러는 Promise 객체의 후속 처리 메소드에게 전달된다.

# 3. 프로미스의 후속 처리 메소드

프로미스로 구현된 비동기 함수는 Promise 객체를 반환하여야 한다. 프로미스로 구현된 비동기 함수를 호출하는 측(promise consumer)에서는 Promise 객체의 후속 처리 메소드 then, catch, finally를 통해 비동기 처리 결과 또는 에러 메시지를 전달받아 후속 처리를 수행한다. Promise 객체는 상태를 갖는다고 하였다. 이 상태에 따라 후속 처리 메소드를 체이닝 방식으로 호출한다. 프로미스의 후속 처리 메소드는 아래와 같다.

-	Promise.prototype.then
: then 메소드는 두 개의 콜백 함수를 인자로 전달 받는다. 첫 번째 콜백 함수는 프로미스의 성공(fulfilled, resolve 함수가 호출된 상태) 시 호출되고 두 번째 함수는 프로미스의 실패(rejected, reject 함수가 호출된 상태) 시 호출된다. then 메소드는 Promise 객체를 반환한다.

-	Promise.prototype.catch
: 예외(비동기 처리에서 발생한 에러와 then 메소드에서 발생한 에러)가 발생하면 호출된다. catch 메소드는 Promise 객체를 반환한다.

-	Promise.prototype.finally
: 프로미스의 성공(fulfilled) 또는 실패(rejected)와 상관없이 무조건 한번은 호출된다. 프로미스의 상태와 상관없이 수행해야할 처리를 finally 메소드에서 처리한다. 또는 then과 catch 메소드에서 공통적으로 수행해야할 것을 finally 메소드에서 처리하면 중복을 피할 수 있다. finally 메소드는 2020년 4월 현재, TC39 프로세스의 stage 4에 제안되어 있다. IE를 제외한 대부분의 브라우저에서 지원하고 있다.

프로미스로 구현한 비동기 함수 get을 사용해 후속 처리를 구현해보자.

```javascript
// GET 요청을 위한 비동기 함수
const promiseGet = url => {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open('GET', url);
    xhr.send();

    xhr.onload = () => {
      if (xhr.status === 200) {
        // 성공적으로 응답을 전달받으면 resolve 함수를 호출한다.
        resolve(JSON.parse(xhr.response));
      } else {
        // 에러 처리를 위해 reject 함수를 호출한다.
        reject(new Error(xhr.status));
      }
    };
  });
};

// promiseGet는 Promise 객체를 반환한다.
promiseGet('https://jsonplaceholder.typicode.com/posts/1')
  .then(res => console.log(res))
  .catch(err => console.error(err))
  .finally(() => console.log('Bye!'));
```

# 4. 프로미스의 에러 처리

위 예제의 비동기 함수 get은 Promise 객체를 반환한다. Promise 객체의 후속 처리 메소드를 사용하여 비동기 처리 결과에 대한 후속 처리를 수행한다. 비동기 처리 시 발생한 에러는 then 메소드의 두 번째 콜백 함수로 처리할 수 있다.

```javascript
promiseGet('https://jsonplaceholder.typicode.com/XXX/1')
  .then(res => console.log(res), err => console.error(err));
```

비동기 처리 시 발생한 에러는 Promise 객체의 후속 처리 메소드 catch을 사용해서 처리할 수도 있다.

```javascript
promiseGet('https://jsonplaceholder.typicode.com/XXX/1')
  .then(res => console.log(res))
  .catch(err => console.error(err));
```

catch 메소드는 에러를 처리한다는 점에서 then 메소드의 두 번째 콜백 함수와 유사하지만 미묘한 차이가 있다. then 메소드의 두 번째 콜백 함수는 비동기 처리에서 발생한 에러(reject 함수가 호출된 상태)만을 캐치한다. 하지만 catch 메소드는 비동기 처리에서 발생한 에러(reject 함수가 호출된 상태)뿐만 아니라 then 메소드 내부에서 발생한 에러도 캐치한다. 따라서 에러 처리는 catch 메소드를 사용하는 편이 보다 효율적이다.

# 5. 프로미스 체이닝

비동기 함수의 처리 결과를 가지고 다른 비동기 함수를 호출해야 하는 경우, 비동기 함수 호출이 중첩(nesting)이 되어 복잡도가 높아지는 콜백 헬이 발생한다. 프로미스는 후속 처리 메소드를 체이닝(chaining)하여 여러 개의 프로미스를 연결하여 사용할 수 있다. 이로써 콜백 헬을 해결한다.

Promise 객체를 반환한 비동기 함수는 프로미스 후속 처리 메소드인 then이나 catch 메소드를 사용할 수 있다. 따라서 then 메소드가 Promise 객체를 반환하도록 하면(then 메소드는 기본적으로 Promise를 반환한다.) 여러 개의 프로미스를 연결하여 사용할 수 있다.

"45.1.1. 콜백 헬"에서 살펴본 콜백 헬이 발생하는 예제를 프로미스를 사용해 구현해보면 아래와 같다.

```javascript
// id가 1인 post의 userId를 취득
promiseGet('https://jsonplaceholder.typicode.com/posts/1')
  // 취득한 post의 userId로 user 정보를 취득
  .then(({ userId }) => promiseGet(`https://jsonplaceholder.typicode.com/users/${userId}`))
  .then(userInfo => console.log(userInfo))
  .catch(err => console.error(err));
```

# 6. 프로미스의 정적 메소드

Promise는 주로 생성자 함수로 사용되지만 함수도 객체이므로 메소드를 갖을 수 있다. Promise 객체는 5가지 정적 메소드를 제공한다.

## 6.1. Promise.resolve / Promise.reject

Promise.resolve와 Promise.reject 메소드는 이미 존재하는 값을 프로미스로 래핑하기 위해 사용한다. 정적 메소드 Promise.resolve 메소드는 인자로 전달된 값을 resolve하는 프로미스를 생성한다.

```javascript
// 배열을 resolve하는 Promise 객체를 생성
const resolvedPromise = Promise.resolve([1, 2, 3]);

resolvedPromise.then(console.log); // [1, 2, 3]
```

위 예제는 아래 예제와 동일하게 동작한다.

```javascript
const resolvedPromise = new Promise(resolve => resolve([1, 2, 3]));

resolvedPromise.then(console.log); // [1, 2, 3]
```

Promise.reject 메소드는 인자로 전달된 값을 reject하는 프로미스를 생성한다.

```javascript
// 에러 객체를 reject하는 Promise 객체를 생성
const rejectedPromise = Promise.reject(new Error('Error!'));

rejectedPromise.catch(console.log); // Error: Error!
```

위 예제는 아래 예제와 동일하게 동작한다.

```javascript
const rejectedPromise = new Promise((resolve, reject) => reject(new Error('Error!')));

rejectedPromise.catch(console.log); // Error: Error!
```

## 6.2. Promise.all

Promise.all 메소드는 프로미스가 담겨 있는 배열 등의 이터러블을 인자로 전달 받는다. 그리고 전달받은 모든 프로미스를 모두 연속적으로 처리하고 그 처리 결과를 resolve하는 새로운 프로미스를 반환한다. 아래 예제를 살펴보자.

```javascript
Promise.all([
  new Promise(resolve => setTimeout(() => resolve(1), 3000)), // 1
  new Promise(resolve => setTimeout(() => resolve(2), 2000)), // 2
  new Promise(resolve => setTimeout(() => resolve(3), 1000))  // 3
]).then(console.log) // [ 1, 2, 3 ]
  .catch(console.error);
```

Promise.all 메소드는 3개의 프로미스를 담은 배열을 전달받았다. 각각의 프로미스는 아래와 같이 동작한다.

-	첫번째 프로미스는 3초 후에 1을 resolve하여 처리 결과를 반환한다.
-	두번째 프로미스는 2초 후에 2을 resolve하여 처리 결과를 반환한다.
-	세번째 프로미스는 1초 후에 3을 resolve하여 처리 결과를 반환한다.

Promise.all 메소드는 전달받은 모든 프로미스를 연속적으로 처리한다. Promise.all은 배열 내 모든 프로미스의 resolve 또는 첫번째 reject를 기다린다.

모든 프로미스의 처리가 성공하면 각각의 프로미스가 resolve한 처리 결과를 배열에 담아 resolve하는 새로운 프로미스를 반환한다. 이때 첫번째 프로미스가 가장 나중에 처리되어도 Promise.all 메소드가 반환하는 프로미스는 첫번째 프로미스가 resolve한 처리 결과부터 차례대로 배열에 담아 그 배열을 resolve하는 새로운 프로미스를 반환한다. 즉, 처리 순서가 보장된다.

프로미스의 처리가 하나라도 실패하면 가장 먼저 실패한 프로미스가 reject한 에러를 reject하는 새로운 프로미스를 즉시 반환한다.

```javascript
Promise.all([
  new Promise((resolve, reject) => setTimeout(() => reject(new Error('Error 1!')), 3000)),
  new Promise((resolve, reject) => setTimeout(() => reject(new Error('Error 2!')), 2000)),
  new Promise((resolve, reject) => setTimeout(() => reject(new Error('Error 3!')), 1000))
]).then(console.log)
  .catch(console.log); // Error: Error 3!
```

위 예제의 경우, 세번째 프로미스가 가장 먼저 실패하므로 세번째 프로미스가 reject한 에러가 catch 메소드로 전달된다.
Promise.all 메소드는 전달 받은 이터러블의 요소가 프로미스가 아닌 경우, Promise.resolve 메소드를 통해 프로미스로 래핑된다.

```javascript
Promise.all([
  1, // => Promise.resolve(1)
  2, // => Promise.resolve(2)
  3  // => Promise.resolve(3)
]).then(console.log) // [1, 2, 3]
  .catch(console.log);
```

아래 예제는 github id로 github 사용자 이름을 취득하는 예제이다.

```javascript
// GET 요청을 위한 비동기 함수
const promiseGet = url => {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open('GET', url);
    xhr.send();

    xhr.onload = () => {
      if (xhr.status === 200) {
        // 성공적으로 응답을 전달받으면 resolve 함수를 호출한다.
        resolve(JSON.parse(xhr.response));
      } else {
        // 에러 처리를 위해 reject 함수를 호출한다.
        reject(new Error(xhr.status));
      }
    };
  });
};

const githubIds = ['jeresig', 'ahejlsberg', 'ungmo2'];

Promise.all(githubIds.map(id => promiseGet(`https://api.github.com/users/${id}`)))
  // [user, user, user] => Promise
  .then(users => users.map(user => user.name))
  // ["John Resig", "Anders Hejlsberg", "Ungmo Lee"]
  .then(console.log)
  .catch(console.error);
```

위 예제의 Promise.all 메소드는 promiseGet 함수가 반환한 3개의 프로미스의 배열을 인수로 전달받고 이 프로미스 들을 모두 연속적으로 처리한다. 모든 프로미스의 처리가 성공하면 Promise.all 메소드는 각각의 프로미스가 resolve한 3개의 사용자 객체가 담긴 배열을 resolve하는 새로운 프로미스를 반환하고 후속 처리 메소드 then에는 3개의 사용자 객체가 담긴 배열이 전달된다.

## 6.3. Promise.race

Promise.race 메소드는 Promise.all 메소드와 동일하게 프로미스가 담겨 있는 배열 등의 이터러블을 인자로 전달 받는다. 그리고 Promise.race 메소드는 Promise.all 메소드처럼 모든 프로미스를 연속적으로 처리하는 것이 아니라 가장 먼저 처리된 프로미스가 resolve한 처리 결과를 resolve하는 새로운 프로미스를 반환한다.

```javascript
Promise.race([
  new Promise(resolve => setTimeout(() => resolve(1), 3000)), // 1
  new Promise(resolve => setTimeout(() => resolve(2), 2000)), // 2
  new Promise(resolve => setTimeout(() => resolve(3), 1000))  // 3
]).then(console.log) // 3
  .catch(console.log);
```

에러가 발생한 경우는 Promise.all 메소드와 동일하게 처리된다. 즉, Promise.race 메소드에 전달된 프로미스 처리가 하나라도 실패하면 가장 먼저 실패한 프로미스가 reject한 에러를 reject하는 새로운 프로미스를 즉시 반환한다.

```javascript
Promise.race([
  new Promise((resolve, reject) => setTimeout(() => reject(new Error('Error 1!')), 3000)),
  new Promise((resolve, reject) => setTimeout(() => reject(new Error('Error 2!')), 2000)),
  new Promise((resolve, reject) => setTimeout(() => reject(new Error('Error 3!')), 1000))
]).then(console.log)
  .catch(console.log); // Error: Error 3!
```

## 6.4. Promise.allSettled

Promise.allSettled 메소드는 프로미스가 담겨 있는 배열 등의 이터러블을 인자로 전달 받는다. 그리고 전달받은 모든 프로미스를 모두 연속적으로 처리하고 그 처리 결과를 배열로 반환한다. 아래 예제를 살펴보자.

```javascript
Promise.allSettled([
  new Promise(resolve => setTimeout(() => resolve(1), 2000)),
  new Promise((resolve, reject) => setTimeout(() => reject(new Error('Error!')), 1000))
]).then(console.log);
/*
[
  {status: "fulfilled", value: 1},
  {status: "rejected", reason: Error: Error! at <anonymous>:3:60}
]
*/
```

Promise.allSettled 메소드가 반환한 배열에는 fulfilled 또는 rejected 상태와는 상관없이 Promise.allSettled 메소드가 인수로 전달받은 모든 프로미스들의 처리 결과가 담겨 있다.

모든 프로미스의 처리 결과를 나타내는 객체는 프로미스가 fulfilled 상태인 경우, 처리 상태를 나타내는 status 프로퍼티와 처리 결과를 나타내는 value 프로퍼티를 갖는다. 프로미스가 rejected 상태인 경우, 처리 상태를 나타내는 status 프로퍼티와 에러를 나타내는 reason 프로퍼티를 갖는다.

```javascript
[
  // 프로미스가 fulfilled 상태인 경우, 프로미스의 처리 결과
  {status: "fulfilled", value: 1},
  // 프로미스가 rejected 상태인 경우, 프로미스의 처리 결과
  {status: "rejected", reason: Error: Error! at <anonymous>:3:60}
]
```
Promise.allSettled 메소드는 2020년 4월 현재, TC39 프로세스의 stage 4에 제안되어 있다. IE를 제외한 대부분의 브라우저에서 지원하고 있다.

# 7. fetch

fetch 함수는 XMLHttpRequest 객체와 마찬가지로 HTTP 요청 전송 기능을 제공하는 Web API이다. fetch 함수는 XMLHttpRequest 객체보다 사용법이 간단하고 프로미스를 지원하기 때문에 비동기 처리를 위한 콜백 패턴의 단점에서 자유롭다. fetch 함수는 비교적 최근에 추가된 Web API로서 인터넷 익스플로어를 제외한 대부분의 브라우저에서 제공하고 있다.

fetch 함수에는 HTTP 요청을 전송할 URL과 HTTP 요청 메소드,  HTTP 요청 헤더, 페이로드 등을 설정한 객체를 전달한다.

```javascript
const promise = fetch(url [, options])
```

fetch 함수는 HTTP 응답을 나타내는 Response 객체를 래핑한 Promise 객체를 반환한다.
fetch 함수로 GET 요청을 전송해 보자. fetch 함수에 첫번째 인수로 HTTP 요청을 전송할 URL만을 전달하면 GET 요청을 전송한다.

```javascript
// https://jsonplaceholder.typicode.com은 Fake REST API를 제공하는 서비스이다.
fetch('https://jsonplaceholder.typicode.com/todos/1')
  .then(response => console.log(response));
```

fetch 함수는 HTTP 응답을 나타내는 Response 객체를 래핑한 프로미스를 반환하므로 후속 처리 메소드 then을 통해 프로미스가 resolve한 Response 객체를 전달받을 수 있다. Response 객체는 HTTP 응답을 나타내는 다양한 프로퍼티를 제공한다.

![](/assets/fs-images/45-1.png)
{: .w-650 }

Response 객체
{: .desc-img}

Response.prototype에는 Response 객체에 포함되어 있는 HTTP 응답 몸체(body)를 위한 다양한 메소드를 제공한다. 예를 들어, fetch 함수가 반환한 프로미스가 래핑하고 있는 HTTP 응답 몸체를 취득하려면 Response.prototype.json 메소드를 사용한다. Response.prototype.json 메소드는 Response 객체에서 HTTP 응답 몸체(response.body)를 취득하여 역직렬화(["43.2.3. JSON.parse"](/fastcampus/ajax#23-jsonparse) 참고)한다.

```javascript
// https://jsonplaceholder.typicode.com은 Fake REST API를 제공하는 서비스이다.
fetch('https://jsonplaceholder.typicode.com/todos/1')
  // response는 HTTP 응답을 나타내는 Response 객체이다.
  // json 메소드를 사용하여 Response 객체에서 HTTP 응답 몸체를 취득하여 역직렬화한다.
  .then(response => response.json())
  // json은 역직렬화된 HTTP 응답 몸체이다.
  .then(json => console.log(json));
  // {userId: 1, id: 1, title: "delectus aut autem", completed: false}
```

fetch 함수를 통해 POST/PATCH/DELETE 요청을 전송해보자. fetch 함수에 첫번째 인수로 HTTP 요청을 전송할 URL과 두번째 인수로 HTTP 요청 메소드, HTTP 요청 헤더, 페이로드 등을 설정한 객체를 전달한다.

```javascript
const request = {
  get(url) {
    return fetch(url);
  },
  post(url, payload) {
    return fetch(url, {
      method: 'POST',
      headers: { 'content-Type': 'application/json' },
      body: JSON.stringify(payload)
    });
  },
  patch(url, payload) {
    return fetch(url, {
      method: 'PATCH',
      headers: { 'content-Type': 'application/json' },
      body: JSON.stringify(payload)
    });
  },
  delete(url) {
    return fetch(url, { method: 'DELETE' });
  }
};

request.get('https://jsonplaceholder.typicode.com/todos/1')
  .then(response => response.json())
  .then(todos => console.log(todos))
  .catch(err => console.error(err));
// {userId: 1, id: 1, title: "delectus aut autem", completed: false}

request.post('https://jsonplaceholder.typicode.com/todos', {
  userId: 1,
  title: 'JavaScript',
  completed: false
})
  .then(response => response.json())
  .then(todos => console.log(todos))
  .catch(err => console.error(err));
// {userId: 1, title: "JavaScript", completed: false, id: 201}

request.patch('https://jsonplaceholder.typicode.com/todos/1', {
  completed: true
})
  .then(response => response.json())
  .then(todos => console.log(todos))
  .catch(err => console.error(err));
// {userId: 1, id: 1, title: "delectus aut autem", completed: true}

request.delete('https://jsonplaceholder.typicode.com/todos/1')
  .then(response => response.json())
  .then(todos => console.log(todos))
  .catch(err => console.error(err));
// {}
```

보다 자세한 내용은 MDN의 [Using Fetch](https://developer.mozilla.org/ko/docs/Web/API/Fetch_API/Fetch의_사용법)를 참고하기 바란다.

- [fetch polyfill](https://github.com/github/fetch)
